name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Lint
        run: chmod +x ./gradlew lintDebug

      - name: Upload Html test report
        uses: actions/upload-artifact@v3
        with:
          name: lint-reports
          path: app/build/reports/lint-result-debug.html

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
