name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Run gradle
        run: ./gradlew lintDebug

      - name: Checkout the code
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@3.13.0
      - name: Build gradle
        run : ./gradlew build

      - name: Upload html test report
        uses: actions/upload-artifact@v3.1.3
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

#      - name: Run a one-line script
#        run: echo Hello, world!
#
#      - name: Run a multi-line script
#        run: |
#          echo Add other actions to build,
#          echo test, and deploy your project.
